<?xml version="1.0" encoding="utf-8"?><Database Name="CNWeb_Pharmacy" Class="DBPharmacyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=win7prox64;Initial Catalog=CNWeb_Pharmacy;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CNWeb_PharmacyConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="MaHoaDon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaThuoc" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MaNhaCungCap" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhaCungCap" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinDaiDien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIAOHANG" Member="GIAOHANGs">
    <Type Name="GIAOHANG">
      <Column Name="HinhThucGiaoHang" Type="System.Char" DbType="NChar(1) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHinhThuc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIOHANG" Member="GIOHANGs">
    <Type Name="GIOHANG">
      <Column Name="MaGH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaThuoc" Type="System.String" DbType="Char(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.String" DbType="Char(35)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HANGSANXUAT" Member="HANGSANXUATs">
    <Type Name="HANGSANXUAT">
      <Column Name="MaHangSX" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHangSX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuocGia" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MaHoaDon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaKhuyenMai" Type="System.String" DbType="NChar(15)" CanBeNull="true" />
      <Column Name="HinhThucGiaoHang" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKhachHang" Type="System.String" DbType="Char(35) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="Char(50) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="Char(90) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MaKM" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TienKM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LOAITHUOC" Member="LOAITHUOCs">
    <Type Name="LOAITHUOC">
      <Column Name="MaLoaiThuoc" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiThuoc" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ParentID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THUOC" Member="THUOCs">
    <Type Name="THUOC">
      <Column Name="MaThuoc" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenThuoc" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CongDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ThanhPhan" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DangThuoc" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiThuoc" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaHangSX" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaNhaCungCap" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="UrlImage" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Tien" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="TimKiem" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>